Make comment
giancarlopernudisegura/cmput404 pull request #124
Opened 2022-03-23 00:50 UTC by jasonexus

Made changes from fixed-get-comment pull request. I had a 400 bad request issue, so hopefully one of you are able to diagnose the issue for me. Thanks in advance!

2022-03-23 16:25 UTC, dellahumanita commented
Neither the View Comments or Comment button is working for me, is this the expected behaviour?

2022-03-23 16:25 UTC, dellahumanita requested changes

2022-03-23 16:25 UTC, dellahumanita commented on src/components/comment-components/CommentList.tsx
> +            {allComments.map((comment) =>
I am getting an error here: `TypeError: allComments.map is not a function`

2022-03-23 17:02 UTC, dalidia requested changes
Have you merged master? I checked the db and you're not using the latest changes for the backend in which we don't use numbers as ID anymore

2022-03-23 17:02 UTC, dalidia commented on src/components/forms/CommentForm.tsx
> +    // const authorData = {
Nitpicky thing but can you remove this commented out code?

2022-03-23 17:02 UTC, dalidia commented on src/components/Post.tsx
> +          {authorName === currentUser && (
Not related to your code, but I assumed that this part was checking the id and not the name. Definitely something we want to change asap, again not in your code but in a different PR

2022-03-23 17:02 UTC, dalidia commented on src/components/Post.tsx
> +          {authorName === currentUser && (
Thanks for changing the variable names, that is helping

2022-03-23 17:02 UTC, dalidia commented on src/components/PostList.tsx
> +                        postId={post.postId}
Nitpicky thing, but can you fix the indentation for <Post >

2022-03-23 17:06 UTC, dalidia commented on src/components/Post.tsx
> +    function getLikesForPosts(authorId: string, postId: string){
don't add extra functionalities like likes for posts. We are checking comments rn

2022-03-24 20:00 UTC, jasonexus commented
Added the model fixes from Dan and made a few adjustments afterwards. Getting comments and making comments should work properly now. Will try to make a few more adjustments since new comments only appear when you refresh the page.

2022-03-24 21:37 UTC, dalidia approved these changes
PR seems good! Thank you!

2022-03-24 21:41 UTC, dellahumanita approved these changes

2022-03-24 21:41 UTC, merged